golf_backend_rails/config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :players
  resources :tees
  resources :rounds
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

golf_backend_rails/app/models/tee.rb
class Tee < ApplicationRecord
  belongs_to :course
end

golf_backend_rails/app/controllers/tees_controller.rb
class TeesController < ApplicationController
  before_action :set_tee, only: %i[ show edit update destroy ]

  # GET /tees or /tees.json
  def index
    @tees = Tee.all
  end

  # GET /tees/1 or /tees/1.json
  def show
  end

  # GET /tees/new
  def new
    @tee = Tee.new
  end

  # GET /tees/1/edit
  def edit
  end

  # POST /tees or /tees.json
  def create
    @tee = Tee.new(tee_params)

    respond_to do |format|
      if @tee.save
        format.html { redirect_to @tee, notice: "Tee was successfully created." }
        format.json { render :show, status: :created, location: @tee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tees/1 or /tees/1.json
  def update
    respond_to do |format|
      if @tee.update(tee_params)
        format.html { redirect_to @tee, notice: "Tee was successfully updated." }
        format.json { render :show, status: :ok, location: @tee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tees/1 or /tees/1.json
  def destroy
    @tee.destroy
    respond_to do |format|
      format.html { redirect_to tees_url, notice: "Tee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tee
      @tee = Tee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tee_params
      params.require(:tee).permit(:course_id, :name, :hole_1, :hole_2, :hole_3, :hole_4, :hole_5, :hole_6, :hole_7, :hole_8, :hole_9, :out, :hole_10, :hole_11, :hole_12, :hole_13, :hole_14, :hole_15, :hole_16, :hole_17, :hole_18, :in, :tot)
    end
end

golf_backend_rails/app/helpers/tees_helper.rb
module TeesHelper
end

golf_backend_rails/app/views/tees/_form.html.erb
<%= simple_form_for(@tee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :course %>
    <%= f.input :name %>
    <%= f.input :hole_1 %>
    <%= f.input :hole_2 %>
    <%= f.input :hole_3 %>
    <%= f.input :hole_4 %>
    <%= f.input :hole_5 %>
    <%= f.input :hole_6 %>
    <%= f.input :hole_7 %>
    <%= f.input :hole_8 %>
    <%= f.input :hole_9 %>
    <%= f.input :out %>
    <%= f.input :hole_10 %>
    <%= f.input :hole_11 %>
    <%= f.input :hole_12 %>
    <%= f.input :hole_13 %>
    <%= f.input :hole_14 %>
    <%= f.input :hole_15 %>
    <%= f.input :hole_16 %>
    <%= f.input :hole_17 %>
    <%= f.input :hole_18 %>
    <%= f.input :in %>
    <%= f.input :tot %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

golf_backend_rails/app/views/tees/edit.html.erb
<h1>Editing Tee</h1>

<%= render 'form', tee: @tee %>

<%= link_to 'Show', @tee %> |
<%= link_to 'Back', tees_path %>

golf_backend_rails/app/views/tees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tees</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Hole 1</th>
      <th>Hole 2</th>
      <th>Hole 3</th>
      <th>Hole 4</th>
      <th>Hole 5</th>
      <th>Hole 6</th>
      <th>Hole 7</th>
      <th>Hole 8</th>
      <th>Hole 9</th>
      <th>Out</th>
      <th>Hole 10</th>
      <th>Hole 11</th>
      <th>Hole 12</th>
      <th>Hole 13</th>
      <th>Hole 14</th>
      <th>Hole 15</th>
      <th>Hole 16</th>
      <th>Hole 17</th>
      <th>Hole 18</th>
      <th>In</th>
      <th>Tot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tees.each do |tee| %>
      <tr>
        <td><%= tee.course_id %></td>
        <td><%= tee.name %></td>
        <td><%= tee.hole_1 %></td>
        <td><%= tee.hole_2 %></td>
        <td><%= tee.hole_3 %></td>
        <td><%= tee.hole_4 %></td>
        <td><%= tee.hole_5 %></td>
        <td><%= tee.hole_6 %></td>
        <td><%= tee.hole_7 %></td>
        <td><%= tee.hole_8 %></td>
        <td><%= tee.hole_9 %></td>
        <td><%= tee.out %></td>
        <td><%= tee.hole_10 %></td>
        <td><%= tee.hole_11 %></td>
        <td><%= tee.hole_12 %></td>
        <td><%= tee.hole_13 %></td>
        <td><%= tee.hole_14 %></td>
        <td><%= tee.hole_15 %></td>
        <td><%= tee.hole_16 %></td>
        <td><%= tee.hole_17 %></td>
        <td><%= tee.hole_18 %></td>
        <td><%= tee.in %></td>
        <td><%= tee.tot %></td>
        <td><%= link_to 'Show', tee %></td>
        <td><%= link_to 'Edit', edit_tee_path(tee) %></td>
        <td><%= link_to 'Destroy', tee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tee', new_tee_path %>

golf_backend_rails/app/views/tees/new.html.erb
<h1>New Tee</h1>

<%= render 'form', tee: @tee %>

<%= link_to 'Back', tees_path %>

golf_backend_rails/app/views/tees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @tee.course_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tee.name %>
</p>

<p>
  <strong>Hole 1:</strong>
  <%= @tee.hole_1 %>
</p>

<p>
  <strong>Hole 2:</strong>
  <%= @tee.hole_2 %>
</p>

<p>
  <strong>Hole 3:</strong>
  <%= @tee.hole_3 %>
</p>

<p>
  <strong>Hole 4:</strong>
  <%= @tee.hole_4 %>
</p>

<p>
  <strong>Hole 5:</strong>
  <%= @tee.hole_5 %>
</p>

<p>
  <strong>Hole 6:</strong>
  <%= @tee.hole_6 %>
</p>

<p>
  <strong>Hole 7:</strong>
  <%= @tee.hole_7 %>
</p>

<p>
  <strong>Hole 8:</strong>
  <%= @tee.hole_8 %>
</p>

<p>
  <strong>Hole 9:</strong>
  <%= @tee.hole_9 %>
</p>

<p>
  <strong>Out:</strong>
  <%= @tee.out %>
</p>

<p>
  <strong>Hole 10:</strong>
  <%= @tee.hole_10 %>
</p>

<p>
  <strong>Hole 11:</strong>
  <%= @tee.hole_11 %>
</p>

<p>
  <strong>Hole 12:</strong>
  <%= @tee.hole_12 %>
</p>

<p>
  <strong>Hole 13:</strong>
  <%= @tee.hole_13 %>
</p>

<p>
  <strong>Hole 14:</strong>
  <%= @tee.hole_14 %>
</p>

<p>
  <strong>Hole 15:</strong>
  <%= @tee.hole_15 %>
</p>

<p>
  <strong>Hole 16:</strong>
  <%= @tee.hole_16 %>
</p>

<p>
  <strong>Hole 17:</strong>
  <%= @tee.hole_17 %>
</p>

<p>
  <strong>Hole 18:</strong>
  <%= @tee.hole_18 %>
</p>

<p>
  <strong>In:</strong>
  <%= @tee.in %>
</p>

<p>
  <strong>Tot:</strong>
  <%= @tee.tot %>
</p>

<%= link_to 'Edit', edit_tee_path(@tee) %> |
<%= link_to 'Back', tees_path %>