golf_backend_rails/config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :players
  resources :tees
  resources :rounds
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

golf_backend_rails/app/models/round.rb
class Round < ApplicationRecord
  belongs_to :course
  has_many :players, dependent: :destroy
  has_many :tees, through: :course
  

  after_save :add_players


  def add_players

    puts self.num_players
    self.num_players.times {
      |i| puts "player #{i +1 }"
      Player.create(round_id: self.id, name: "Player Name", hole_1: 0, hole_2: 0, hole_3: 0, hole_4: 0, hole_5: 0, hole_6: 0, hole_7: 0, hole_8: 0, hole_9: 0, out: 0, hole_10: 0, hole_11: 0, hole_12: 0, hole_13: 0, hole_14: 0, hole_15: 0, hole_16: 0, hole_17: 0, hole_18: 0, in: 0, total: 0 )
    }

  end
end

golf_backend_rails/app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :set_round, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token


  # GET /rounds or /rounds.json
  def index
    @rounds = Round.all
    render json: @rounds, include:
    [:course, :players] 
   end

  # GET /rounds/1 or /rounds/1.json
  def show
    render json: @round, include:
    [:course, :players, :tees]
  end

  # GET /rounds/new
  def new
    @round = Round.new
  end

  # GET /rounds/1/edit
  def edit
  end

  # POST /rounds or /rounds.json
  def create
    @round = Round.new(round_params)
    puts round_params

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: "Round was successfully created." }
        format.json { render :show, status: :created, location: @round }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rounds/1 or /rounds/1.json
  def update
    respond_to do |format|
      if @round.update(round_params)
        format.html { redirect_to @round, notice: "Round was successfully updated." }
        format.json { render :show, status: :ok, location: @round }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1 or /rounds/1.json
  def destroy
    @round.destroy
    respond_to do |format|
      format.html { redirect_to rounds_url, notice: "Round was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def round_params
      params.require(:round).permit(:course_id, :num_players, :user_id)
    end
end

golf_backend_rails/app/helpers/rounds_helper.rb
module RoundsHelper
end

golf_backend_rails/app/views/rounds/_form.html.erb
<%= simple_form_for(@round) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :course %>
    <%= f.input :num_players %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

golf_backend_rails/app/views/rounds/edit.html.erb
<h1>Editing Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

golf_backend_rails/app/views/rounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rounds</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Num players</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rounds.each do |round| %>
      <tr>
        <td><%= round.course.name %></td>
        <td><%= round.num_players %></td>
        <td><%= round.user_id %></td>
        <td><%= link_to 'Show', round %></td>
        <td><%= link_to 'Edit', edit_round_path(round) %></td>
        <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Round', new_round_path %>

golf_backend_rails/app/views/rounds/new.html.erb
<h1>New Round</h1>

<%= render 'form', round: @round %>

<%= link_to 'Back', rounds_path %>

golf_backend_rails/app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @round.course.name %>
</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hole 1</th>
      <th>Hole 2</th>
      <th>Hole 3</th>
      <th>Hole 4</th>
      <th>Hole 5</th>
      <th>Hole 6</th>
      <th>Hole 7</th>
      <th>Hole 8</th>
      <th>Hole 9</th>
      <th>Out</th>
      <th>Hole 10</th>
      <th>Hole 11</th>
      <th>Hole 12</th>
      <th>Hole 13</th>
      <th>Hole 14</th>
      <th>Hole 15</th>
      <th>Hole 16</th>
      <th>Hole 17</th>
      <th>Hole 18</th>
      <th>In</th>
      <th>Tot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @round.course.tees.each do |tee| %>
      <tr>
        <td><%= tee.name %></td>
        <td><%= tee.hole_1 %></td>
        <td><%= tee.hole_2 %></td>
        <td><%= tee.hole_3 %></td>
        <td><%= tee.hole_4 %></td>
        <td><%= tee.hole_5 %></td>
        <td><%= tee.hole_6 %></td>
        <td><%= tee.hole_7 %></td>
        <td><%= tee.hole_8 %></td>
        <td><%= tee.hole_9 %></td>
        <td><%= tee.out %></td>
        <td><%= tee.hole_10 %></td>
        <td><%= tee.hole_11 %></td>
        <td><%= tee.hole_12 %></td>
        <td><%= tee.hole_13 %></td>
        <td><%= tee.hole_14 %></td>
        <td><%= tee.hole_15 %></td>
        <td><%= tee.hole_16 %></td>
        <td><%= tee.hole_17 %></td>
        <td><%= tee.hole_18 %></td>
        <td><%= tee.in %></td>
        <td><%= tee.tot %></td>
        <td><%= link_to 'Show', tee %></td>
        <td><%= link_to 'Edit', edit_tee_path(tee) %></td>
        <td><%= link_to 'Destroy', tee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     
    <% end %>
    <% @round.players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.hole_1 %></td>
        <td><%= player.hole_2 %></td>
        <td><%= player.hole_3 %></td>
        <td><%= player.hole_4 %></td>
        <td><%= player.hole_5 %></td>
        <td><%= player.hole_6 %></td>
        <td><%= player.hole_7 %></td>
        <td><%= player.hole_8 %></td>
        <td><%= player.hole_9 %></td>
        <td><%= player.out %></td>
        <td><%= player.hole_10 %></td>
        <td><%= player.hole_11 %></td>
        <td><%= player.hole_12 %></td>
        <td><%= player.hole_13 %></td>
        <td><%= player.hole_14 %></td>
        <td><%= player.hole_15 %></td>
        <td><%= player.hole_16 %></td>
        <td><%= player.hole_17 %></td>
        <td><%= player.hole_18 %></td>
        <td><%= player.in %></td>
        <td><%= player.total %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </tbody>
</table>







<table>


  <tbody>

</table>

<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>