golf_backend_rails/config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :players
  resources :tees
  resources :rounds
  resources :courses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

golf_backend_rails/app/models/player.rb
class Player < ApplicationRecord
  belongs_to :round
end

golf_backend_rails/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:round_id, :name, :hole_1, :hole_2, :hole_3, :hole_4, :hole_5, :hole_6, :hole_7, :hole_8, :hole_9, :out, :hole_10, :hole_11, :hole_12, :hole_13, :hole_14, :hole_15, :hole_16, :hole_17, :hole_18, :in, :total)
    end
end

golf_backend_rails/app/helpers/players_helper.rb
module PlayersHelper
end

golf_backend_rails/app/views/players/_form.html.erb
<%= simple_form_for(@player) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :round %>
    <%= f.input :name %>
    <%= f.input :hole_1 %>
    <%= f.input :hole_2 %>
    <%= f.input :hole_3 %>
    <%= f.input :hole_4 %>
    <%= f.input :hole_5 %>
    <%= f.input :hole_6 %>
    <%= f.input :hole_7 %>
    <%= f.input :hole_8 %>
    <%= f.input :hole_9 %>
    <%= f.input :out %>
    <%= f.input :hole_10 %>
    <%= f.input :hole_11 %>
    <%= f.input :hole_12 %>
    <%= f.input :hole_13 %>
    <%= f.input :hole_14 %>
    <%= f.input :hole_15 %>
    <%= f.input :hole_16 %>
    <%= f.input :hole_17 %>
    <%= f.input :hole_18 %>
    <%= f.input :in %>
    <%= f.input :total %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

golf_backend_rails/app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

golf_backend_rails/app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Round</th>
      <th>Name</th>
      <th>Hole 1</th>
      <th>Hole 2</th>
      <th>Hole 3</th>
      <th>Hole 4</th>
      <th>Hole 5</th>
      <th>Hole 6</th>
      <th>Hole 7</th>
      <th>Hole 8</th>
      <th>Hole 9</th>
      <th>Out</th>
      <th>Hole 10</th>
      <th>Hole 11</th>
      <th>Hole 12</th>
      <th>Hole 13</th>
      <th>Hole 14</th>
      <th>Hole 15</th>
      <th>Hole 16</th>
      <th>Hole 17</th>
      <th>Hole 18</th>
      <th>In</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.round_id %></td>
        <td><%= player.name %></td>
        <td><%= player.hole_1 %></td>
        <td><%= player.hole_2 %></td>
        <td><%= player.hole_3 %></td>
        <td><%= player.hole_4 %></td>
        <td><%= player.hole_5 %></td>
        <td><%= player.hole_6 %></td>
        <td><%= player.hole_7 %></td>
        <td><%= player.hole_8 %></td>
        <td><%= player.hole_9 %></td>
        <td><%= player.out %></td>
        <td><%= player.hole_10 %></td>
        <td><%= player.hole_11 %></td>
        <td><%= player.hole_12 %></td>
        <td><%= player.hole_13 %></td>
        <td><%= player.hole_14 %></td>
        <td><%= player.hole_15 %></td>
        <td><%= player.hole_16 %></td>
        <td><%= player.hole_17 %></td>
        <td><%= player.hole_18 %></td>
        <td><%= player.in %></td>
        <td><%= player.total %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

golf_backend_rails/app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

golf_backend_rails/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Round:</strong>
  <%= @player.round_id %>
</p>
<p>
  <strong>Player Id:</strong>
  <%= @player.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Hole 1:</strong>
  <%= @player.hole_1 %>
</p>

<p>
  <strong>Hole 2:</strong>
  <%= @player.hole_2 %>
</p>

<p>
  <strong>Hole 3:</strong>
  <%= @player.hole_3 %>
</p>

<p>
  <strong>Hole 4:</strong>
  <%= @player.hole_4 %>
</p>

<p>
  <strong>Hole 5:</strong>
  <%= @player.hole_5 %>
</p>

<p>
  <strong>Hole 6:</strong>
  <%= @player.hole_6 %>
</p>

<p>
  <strong>Hole 7:</strong>
  <%= @player.hole_7 %>
</p>

<p>
  <strong>Hole 8:</strong>
  <%= @player.hole_8 %>
</p>

<p>
  <strong>Hole 9:</strong>
  <%= @player.hole_9 %>
</p>

<p>
  <strong>Out:</strong>
  <%= @player.out %>
</p>

<p>
  <strong>Hole 10:</strong>
  <%= @player.hole_10 %>
</p>

<p>
  <strong>Hole 11:</strong>
  <%= @player.hole_11 %>
</p>

<p>
  <strong>Hole 12:</strong>
  <%= @player.hole_12 %>
</p>

<p>
  <strong>Hole 13:</strong>
  <%= @player.hole_13 %>
</p>

<p>
  <strong>Hole 14:</strong>
  <%= @player.hole_14 %>
</p>

<p>
  <strong>Hole 15:</strong>
  <%= @player.hole_15 %>
</p>

<p>
  <strong>Hole 16:</strong>
  <%= @player.hole_16 %>
</p>

<p>
  <strong>Hole 17:</strong>
  <%= @player.hole_17 %>
</p>

<p>
  <strong>Hole 18:</strong>
  <%= @player.hole_18 %>
</p>

<p>
  <strong>In:</strong>
  <%= @player.in %>
</p>

<p>
  <strong>Total:</strong>
  <%= @player.total %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>